### ISSUE TITLE
Does not support using IP Addresses

### ISSUE THREAD

**Issue by xandaaah** [Sch8ill/MCClient#14]
bottom text

**Comment by xandaaah** [comment]
I realized I was using the pipi package

**Comment by xandaaah** [comment]
I just compiled, uninstalled the pipi, and installed the .whl. Still did not work.

**Comment by Sch8ill** [comment]
Hello @Xanderplayz16,

Thank you for reporting the issue. Could you please provide me with more information so that i can better understand your problem? What exactly were you trying to do when you encountered the issue?

Additionally, would you mind sending me your error log and describing your environment a bit more? Specifically, please let me know what operating system and version of Python you are using. Also, just to confirm, did you mean "PyPI" when you mentioned "pipi"? 😊

Best regards,
Till

**Comment by xandaaah** [comment]
![image](https://user-images.githubusercontent.com/74632800/229899708-fad7e4b5-b695-44fc-8c5c-701f49487d83.png)

**Comment by xandaaah** [comment]
Yes, I meant pypi. 
Python 3.10.9
Windows 11
Dell XPS 8940

**Comment by Sch8ill** [comment]
Hello @Xanderplayz16,

Based on the error log you provided, it appears that there may have been an issue with your DNS server. It's possible that you were trying to look up a domain that didn't exist. While I'm not an expert in DNS, that's one potential explanation for the exception you encountered. Another possible cause could be a poor internet connection.

To help me better understand the issue, it would be very helpful if you could check whether the domain referenced in the variable "i" exists publicly, not just on a local DNS server. This may provide some insight into what's causing the issue.

Best regards,
Till

**Comment by Sch8ill** [comment]
Is this error occurring frequently or is it a rare occurrence?

**Comment by xandaaah** [comment]
Frequently

**Comment by xandaaah** [comment]
I just tried Google's DNS server (8.8.8.8) and even that does not work.

**Comment by Sch8ill** [comment]
After reviewing your issue, it seems that there may be a problem with your internet connection or with dnspython, which is the DNS client that mcclient-lib uses. If you're performing a high volume of DNS/SLP lookups in a short period of time, it's possible that your router or the responding DNS server could drop some of your requests. This may be especially true if you're running port scans, for example.

Unfortunately, I'm not able to fix the issue for you. I apologize for any inconvenience this may cause. If the error isn't occurring consistently, you could try implementing a retry logic in your code to see if that helps mitigate the issue.

Or try implementing your code with [minestat](https://github.com/fragland/minestat).

I hope this helps 🙃

**Comment by xandaaah** [comment]
I am looking up IP addresses… You do not need dns for that.

>

**Comment by Sch8ill** [comment]
Thats correct @Xanderplayz16 . You don't need DNS to connect to servers who's address is an IP address.

My suggestion to you would be to check if your  IP address is valid, the libary will try to lookup the address using DNS If not, because it thinks you are trying to use a domain to connect to a server... (This may cause the errors you encounterd)

An IP address is a string of four dot seperated numbers between 0 and 255, just to be clear. (IPv6 is a bit different though)

**Comment by DJStompZone** [comment]
@Xanderplayz16 Maybe this would benefit from a bit of additional context. Would you be able to share the specific code in serverscan2.py that produces the error? If needed, you can substitute the digits in any hard-coded IP addresses with zeroes or asterisks.

**Comment by Sch8ill** [comment]
@DJStompZone You are able to add asterisks to IP addresses, this would define an IP range though. It is impossible to connect to an IP range, it's an IP range not an IP address...

**Comment by DJStompZone** [comment]
> @Xanderplayz16 Maybe this would benefit from a bit of additional context. Would you be able to share the specific code in serverscan2.py that produces the error? If needed, you can substitute the digits in any hard-coded IP addresses with zeroes or asterisks.

> @DJStompZone It is impossible to connect to an IP range, it's an IP range not an IP address...

Sorry, I should clarify what I meant:
  > Would you be able to share the specific code in serverscan2.py that produces the error? If you do, be sure to substitute the any hard-coded IP addresses **in the shared code** with zeroes or asterisks.

**Comment by xandaaah** [comment]
slp_client = SLPClient("*.*.*.*”, port=25565)
res = slp_client.get_status()


>

**Comment by Sch8ill** [comment]
@Xanderplayz16 
"*.*.*.*" is not an IP address, it's an IP range. 
You can't connect to an IP range because it's a notation to list multiple IP addresses (the entire internet in this case) 😁

**Comment by xandaaah** [comment]
The *.*.*.* is just a placeholder (I do not want to leak ips)
>

**Comment by Sch8ill** [comment]
@Xanderplayz16 
Well, I don't see a problem then. 
The client should work if provided with proper input.

**Comment by Sch8ill** [comment]
Or is the server using a special software that isn't vanilla minecraft?
These third party Minecraft versions sometimes don't implement the Minecraft protocol correctly.

**Comment by xandaaah** [comment]
It is probably that.

>
