### ISSUE TITLE
Getting around "Max retries exceeded"

### ISSUE THREAD

**Issue by alexpavloff** [Sch8ill/MCClient#19]
I tried to use Server List Ping with various Minecraft servers and got a plenty of _"Max retries exceeded"_ exceptions.
As it seems to me the reason is the fact that `socket.recv` doesn't guarantee to return data of the same size as its bufsize parameter. It often fails when a server has a "heavy" favicon, like 5 kBs. So `BaseClient._recv` method often signalize a packet loss, but `SLPClient._status_request` method can't deal with it, I think you need to rewrite `BaseClient._recv` like [this (search for 'myreceive' method)](https://docs.python.org/3/howto/sockets.html). This approach or just adding some empty print statements  helped me avoid the expection above 😄

**Comment by Sch8ill** [comment]
@alexpavloff  This issue has been fixed in version 1.1.1. I apologize for the delay in resolving this matter.

**Comment by Sch8ill** [comment]
@alexpavloff This issue has been fixed in version 1.1.1. I apologize for the delay in resolving this matter.
